### PR TITLE
nixed

### PR DESCRIPTION
**Pull request by jagajaga**
Create derivation for a [Nix package manager](http://nixos.org/nix/).

If you have nix installed, you can just do `nix-build` (to just locally build) or `nix-env -i mpdas -f default.nix` (to install as user).

 P.S. Going to submit your program to official repo of `nixpkgs`, when you release 0.4 :)

### CODE REVIEW

**Comment by hrkfdn** [comment]
Hey, thanks a lot! Is there any benefit in having this in the upstream codebase?

**Comment by jagajaga** [comment]
Yeah! That helps nix users a lot (I've wrote why in the PR message). :smile:

**Comment by hrkfdn** [comment]
Yea, I read it ;)

Just wondering, because I'd prefer to avoid having this in upstream, because given the amount of packaging systems it certainly wouldn't stop with nix. Isn't there some central repository keeping track of all the nix derivations?

**Comment by jagajaga** [comment]
Yes, there is https://github.com/NixOS/nixpkgs. I will add your pkg there after 0.4 release :)

**Comment by hrkfdn** [comment]
Hey there. I'm going to close this one as I don't think this should be part of the upstream repository. For one, because I can not maintain it (I don't use nixOS) and also because I otherwise I'd have to add the package build files for other distributions. I hope you understand, I appreciate the effort, though ;)

**Pull request closed without merging**
